//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.DotNet.MSBuildSdkResolver {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.DotNet.MSBuildSdkResolver.Strings2", typeof(Strings2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workload definition &apos;{0}&apos; is a concrete dev workload but has no description.
        /// </summary>
        internal static string ConcreteWorkloadHasNoDescription {
            get {
                return ResourceManager.GetString("ConcreteWorkloadHasNoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workload definition &apos;{0}&apos; in manifest &apos;{1}&apos; [{2}] conflicts with manifest &apos;{3}&apos; [{4}].
        /// </summary>
        internal static string ConflictingWorkloadDefinition {
            get {
                return ResourceManager.GetString("ConflictingWorkloadDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workload pack &apos;{0}&apos; in manifest &apos;{1}&apos; [{2}] conflicts with manifest &apos;{3}&apos; [{4}].
        /// </summary>
        internal static string ConflictingWorkloadPack {
            get {
                return ResourceManager.GetString("ConflictingWorkloadPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclic workload redirect &apos;{0}&apos; in manifest &apos;{1}&apos; [{2}].
        /// </summary>
        internal static string CyclicWorkloadRedirect {
            get {
                return ResourceManager.GetString("CyclicWorkloadRedirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate key &apos;{0}&apos; at offset {1}.
        /// </summary>
        internal static string DuplicateKeyAtOffset {
            get {
                return ResourceManager.GetString("DuplicateKeyAtOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifest provider {0} returned a duplicate manifest ID &apos;{1}&apos; [{2}] that conflicts with existing manifest [{3}].
        /// </summary>
        internal static string DuplicateManifestID {
            get {
                return ResourceManager.GetString("DuplicateManifestID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected boolean value at offset {0}.
        /// </summary>
        internal static string ExpectedBoolAtOffset {
            get {
                return ResourceManager.GetString("ExpectedBoolAtOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected integer value at offset {0}.
        /// </summary>
        internal static string ExpectedIntegerAtOffset {
            get {
                return ResourceManager.GetString("ExpectedIntegerAtOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected string value at offset {0}.
        /// </summary>
        internal static string ExpectedStringAtOffset {
            get {
                return ResourceManager.GetString("ExpectedStringAtOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected {0} token at offset {1}.
        /// </summary>
        internal static string ExpectedTokenAtOffset {
            get {
                return ResourceManager.GetString("ExpectedTokenAtOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document ended prematurely.
        /// </summary>
        internal static string IncompleteDocument {
            get {
                return ResourceManager.GetString("IncompleteDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid version: {0}.
        /// </summary>
        internal static string InvalidManifestVersion {
            get {
                return ResourceManager.GetString("InvalidManifestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not find workload manifest dependency &apos;{0}&apos; required by manifest &apos;{1}&apos; [{2}].
        /// </summary>
        internal static string ManifestDependencyMissing {
            get {
                return ResourceManager.GetString("ManifestDependencyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workload manifest dependency &apos;{0}&apos; version &apos;{1}&apos; is lower than version &apos;{2}&apos; required by manifest &apos;{3}&apos; [{4}].
        /// </summary>
        internal static string ManifestDependencyVersionTooLow {
            get {
                return ResourceManager.GetString("ManifestDependencyVersionTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find workload &apos;{0}&apos; extended by workload &apos;{1}&apos; in manifest &apos;{2}&apos; [{3}].
        /// </summary>
        internal static string MissingBaseWorkload {
            get {
                return ResourceManager.GetString("MissingBaseWorkload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing or invalid manifest version.
        /// </summary>
        internal static string MissingOrInvalidManifestVersion {
            get {
                return ResourceManager.GetString("MissingOrInvalidManifestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing kind for workload pack &apos;{0}&apos;.
        /// </summary>
        internal static string MissingWorkloadPackKind {
            get {
                return ResourceManager.GetString("MissingWorkloadPackKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing version for workload pack &apos;{0}&apos;.
        /// </summary>
        internal static string MissingWorkloadPackVersion {
            get {
                return ResourceManager.GetString("MissingWorkloadPackVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect workload &apos;{0}&apos; has keys other than &apos;redirect-to&apos;.
        /// </summary>
        internal static string RedirectWorkloadHasOtherKeys {
            get {
                return ResourceManager.GetString("RedirectWorkloadHasOtherKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected token &apos;{0}&apos; at offset {1}.
        /// </summary>
        internal static string UnexpectedTokenAtOffset {
            get {
                return ResourceManager.GetString("UnexpectedTokenAtOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown key &apos;{0}&apos; at offset {1}.
        /// </summary>
        internal static string UnknownKeyAtOffset {
            get {
                return ResourceManager.GetString("UnknownKeyAtOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown workload definition kind &apos;{0}&apos; at offset {1}.
        /// </summary>
        internal static string UnknownWorkloadDefinitionKind {
            get {
                return ResourceManager.GetString("UnknownWorkloadDefinitionKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown workload pack kind &apos;{0}&apos; at offset {1}.
        /// </summary>
        internal static string UnknownWorkloadPackKind {
            get {
                return ResourceManager.GetString("UnknownWorkloadPackKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unresolved target &apos;{0}&apos; for workload redirect &apos;{1}&apos; in manifest &apos;{2}&apos; [{3}].
        /// </summary>
        internal static string UnresolvedWorkloadRedirect {
            get {
                return ResourceManager.GetString("UnresolvedWorkloadRedirect", resourceCulture);
            }
        }
    }
}
