name: "Tag and push to GitHub"
description: "Tag and push to GitHub"

runs:
  using: "composite"
  steps:
  - name: Checkout
    uses: actions/checkout@v2

  - name: Setup .NET SDK
    uses: actions/setup-dotnet@v1
    with:
      dotnet-version: '9.0.300'

  - uses: dotnet/nbgv@f088059084cb5d872e9d1a994433ca6440c2bf72 # v0.4.2
    name: NBGV
    id: nbgv
    with:
      toolVersion: 3.6.139
      setAllVars: true

  - name: "Tag and push to GitHub"
    shell: pwsh
    run: |
      git config user.email "info@platform.uno"
      git config user.name "Uno DevOps"
      git tag $env:NBGV_SemVer2
      git push origin $env:NBGV_SemVer2