name: "Tag and push to GitHub"
description: "Tag and push to GitHub"

runs:
  using: "composite"
  steps:
  - name: Checkout
    uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

  - name: Setup .NET SDK
    uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
    with:
      dotnet-version: '9.0.300'

  - uses: dotnet/nbgv@705dad19ab067f12f4e9eeaa60812e01edef5d25 # v0.5.2
    name: NBGV
    id: nbgv
    with:
      toolVersion: 3.6.139
      setAllVars: true

  - name: "Tag and push to GitHub"
    shell: pwsh
    run: |
      git config user.email "info@platform.uno"
      git config user.name "Uno DevOps"
      git tag $env:NBGV_SemVer2
      git push origin $env:NBGV_SemVer2