name: CI

on: 
  push:
    branches:
      - main
      - release/**

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - release/**

  schedule:
    - cron: '0 0 * * *' # every day at midnight

env:
  GitVersion_Version: 5.10.3

concurrency: 
  group: ${{github.workflow}} - ${{github.ref}}
  cancel-in-progress: true
  
jobs:
  build_tool:
    name: Diagnostics
    runs-on: windows-latest
    steps:
    - name: Diagnostics - CI
      shell: cmd
      run: |
        set
        runas /user:%COMPUTERNAME%\runneradmin powershell -Command exit
#        runas /noprofile /user:%COMPUTERNAME%\runneradmin powershell -Command Get-ExecutionPolicy -Scope CurrentUser
